on:
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name NtpTime
      - name: Pester
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          report_name: module_tests
          report_title: Test results
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test results
        shell: pwsh
        run: |
          Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
          Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
          Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'